#!/bin/sh

export PATH=/usr/bin:/bin:/usr/sbin:/sbin

identifier="com.jamf.setupmanager.finished"
launchDaemonPath="/Library/LaunchDaemons/${identifier}.plist"

if [ "$3" != "/" ]; then
  echo "not installing on startup volume, exiting preinstall"
  exit 0
fi

if launchctl list | grep -q "$identifier"; then
  echo "unloading launchDaemon for $identifier"
  launchctl unload "$identifier"
fi

# always exit success regardless of exit code of above commands
exit 0
